Support passing the private key in a command line argument

diff --git a/wgc b/wgc
--- a/wgc
+++ b/wgc
@@ -21,9 +21,10 @@
 
 show_usage() {
   cat <<EOF
-Usage: $THIS [-c|--cfgdir config_dir] [start <vpn>|stop <vpn>|status <vpn>|active|list|exec <vpn> <command>]
+Usage: $THIS [-c|--cfgdir config_dir] [-p|--prvkey private_key] [start <vpn>|stop <vpn>|status <vpn>|active|list|exec <vpn> <command>]
 
 If omitted, config_dir defaults to /etc/wireguard
+If omitted, private_key must be given in the config file
 
 <vpn> should match the config file name config_dir/<vpn>.conf
 
@@ -96,7 +97,7 @@ parse_config_file() {
   done < "$CONFIG_FILE"
   [[ "$WARNINGS" ]] && echo -e "$N Warnings for $CONFIG_FILE:$WARNINGS" >&2
   local k
-  for k in Address PrivateKey PublicKey Endpoint AllowedIPs; do
+  for k in Address PublicKey Endpoint AllowedIPs; do
     [[ ${!k} ]] || { echo "$N ERROR: Missing required key '$k' in file $CONFIG_FILE" >&2; return 1; }
   done
 }
@@ -375,6 +376,8 @@ start_vpn() {
 
   # get parameters from config file named $DEV
   parse_config_file $DEV || return 1
+  local CONFIG_FILE="$CFGDIR/$DEV.conf"
+  [[ -v PrivateKey ]] || { echo "$N ERROR: Missing required key 'PrivateKey' in file $CONFIG_FILE" >&2; return 1; }
 
   if ip netns exec $NAMESPACE ip -c address show $DEV 2>/dev/null; then
     echo "$N $DEV is already connected"
@@ -487,10 +490,11 @@ check_dependencies || exit 1
 
 LONGOPTIONS=
 LONGOPTIONS+=cfgdir
+LONGOPTIONS+=,prvkey
 
 declare -r LONGOPTIONS
 
-OPTS="$(getopt -o c: --longoptions $LONGOPTIONS -- "$@")" || { show_usage && exit 1; }
+OPTS="$(getopt -o c:p: --longoptions $LONGOPTIONS -- "$@")" || { show_usage && exit 1; }
 eval set -- "$OPTS"
 unset OPTS
 
@@ -498,6 +502,10 @@ while [[ -v 1 ]]; do
   case "$1" in
     -c | --cfgdir)
       CFGDIR=$2
+      shift 2
+      ;;
+    -p | --prvkey)
+      PrivateKey=$2
       shift 2
       ;;
     --)
